/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF(
    "/pirateKit/Models/glTF/boat_large.gltf",
  );

  return (
    <group {...props}>
      {nodes && (
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.boat_large_8angles as THREE.Mesh).geometry} // Type assertion
          material={materials.wood}
          position={[1.31, 0, -9.962]}
        />
      )}
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/boat_large.gltf");
