/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF(
    "/pirateKit/Models/glTF/boat_small.gltf",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.boat_small_8angles.geometry}
        material={materials.wood}
        position={[-0.325, 0, -9.962]}
      />
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/boat_small.gltf");
