/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF(
    "/pirateKit/Models/glTF/bottleLarge.gltf",
  );
  return (
    <group {...props} dispose={null}>
      <group position={[-3.451, 0, -6.373]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bottleLarge_2.geometry}
          material={materials.textile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bottleLarge_3.geometry}
          material={materials.wood}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/bottleLarge.gltf");
