/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps<THREE.Group>) {
  const { nodes, materials } = useGLTF("/pirateKit/Models/glTF/bottle.gltf");

  return (
    <group {...props}>
      {nodes && materials && (
        <group position={[-3.838, 0, -6.409]} scale={0.71}>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.bottle_2 as THREE.Mesh)?.geometry}
            material={materials.leaves}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.bottle_3 as THREE.Mesh)?.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.bottle_4 as THREE.Mesh)?.geometry}
            material={materials.textile}
          />
        </group>
      )}
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/bottle.gltf");
