/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF("/pirateKit/Models/glTF/cannon.gltf");

  return (
    <group {...props}>
      {nodes && materials && (
        <group position={[1.187, 0, -7.725]}>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.cannon_2 as THREE.Mesh)?.geometry}
            material={materials.iron}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.cannon_3 as THREE.Mesh)?.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.barrel as THREE.Mesh)?.geometry}
            material={materials.iron}
            position={[0, 0.283, -0.067]}
          />
        </group>
      )}
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/cannon.gltf");
