/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps<THREE.Group>) {
  const { nodes, materials } = useGLTF(
    "/pirateKit/Models/glTF/cannonBall.gltf"
  );

  return (
    <group {...props}>
      {nodes && materials && (
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.cannonBall_1 as THREE.Mesh)?.geometry}
          material={materials.iron}
          position={[-1.509, 0.07, -7.772]}
        />
      )}
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/cannonBall.gltf");
