/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three"; // Import THREE
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps<THREE.Group>) {
  const { nodes, materials } = useGLTF(
    "/pirateKit/Models/glTF/cannonLarge.gltf"
  );

  return (
    <group {...props}>
      {nodes && materials && (
        <group position={[-0.942, 0, -7.47]}>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.cannonLarge_2 as THREE.Mesh)?.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.cannonLarge_3 as THREE.Mesh)?.geometry}
            material={materials.iron}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.barrel_1 as THREE.Mesh)?.geometry}
            material={materials.iron}
            position={[0, 0.348, -0.067]}
          />
        </group>
      )}
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/cannonLarge.gltf");
