/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/cannon.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[1.187, 0, -7.725]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cannon_2.geometry}
          material={materials.iron}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cannon_3.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.barrel.geometry}
          material={materials.iron}
          position={[0, 0.283, -0.067]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cannon.gltf");
