/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three"; // Import THREE
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps<THREE.Group>) {
  const { nodes, materials } = useGLTF(
    "/pirateKit/Models/glTF/cannonMobile.gltf"
  );

  return (
    <group {...props}>
      <group position={[0.122, 0, -7.725]}>
        {nodes && materials && (
          <>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.cannonMobile_8angles_1 as THREE.Mesh)?.geometry}
              material={materials.iron}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.cannonMobile_8angles_2 as THREE.Mesh)?.geometry}
              material={materials.wood}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.barrel_2 as THREE.Mesh)?.geometry}
              material={materials.iron}
              position={[0, 0.45, -0.067]}
            />
            <group position={[-0.217, 0.128, 0.262]}>
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.wheel_backLeft_1 as THREE.Mesh)?.geometry}
                material={materials.iron}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.wheel_backLeft_2 as THREE.Mesh)?.geometry}
                material={materials.wood}
              />
            </group>
            <group
              position={[0.217, 0.128, 0.262]}
              rotation={[Math.PI, 0, Math.PI]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.wheel_backLeft_1 as THREE.Mesh)?.geometry}
                material={materials.iron}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.wheel_backLeft_2 as THREE.Mesh)?.geometry}
                material={materials.wood}
              />
            </group>
            <group position={[-0.217, 0.128, -0.197]}>
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.wheel_backLeft_1 as THREE.Mesh)?.geometry}
                material={materials.iron}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.wheel_backLeft_2 as THREE.Mesh)?.geometry}
                material={materials.wood}
              />
            </group>
            <group
              position={[0.217, 0.128, -0.197]}
              rotation={[Math.PI, 0, Math.PI]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.wheel_backLeft_1 as THREE.Mesh)?.geometry}
                material={materials.iron}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.wheel_backLeft_2 as THREE.Mesh)?.geometry}
                material={materials.wood}
              />
            </group>
          </>
        )}
      </group>
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/cannonMobile.gltf");
