/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three"; // Import THREE
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps<THREE.Group>) {
  const { nodes, materials } = useGLTF("/pirateKit/Models/glTF/chest.gltf");

  return (
    <group {...props}>
      <group position={[-2.63, 0, -6.294]} scale={0.64}>
        {nodes && materials && (
          <>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.chest_2 as THREE.Mesh)?.geometry}
              material={materials.wood}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.chest_3 as THREE.Mesh)?.geometry}
              material={materials.stone}
            />
            <group position={[0, 0.515, 0.265]}>
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.lid_1 as THREE.Mesh)?.geometry}
                material={materials.wood}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.lid_2 as THREE.Mesh)?.geometry}
                material={materials.stone}
              />
            </group>
          </>
        )}
      </group>
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/chest.gltf");
