/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF("/pirateKit/Models/glTF/chest.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[-2.63, 0, -6.294]} scale={0.64}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chest_2.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chest_3.geometry}
          material={materials.stone}
        />
        <group position={[0, 0.515, 0.265]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.lid_1.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.lid_2.geometry}
            material={materials.stone}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/chest.gltf");
