/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three"; // Import THREE
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF(
    "/pirateKit/Models/glTF/formation_rock.gltf",
  );

  return (
    <group {...props}>
      {nodes && materials && (
        <group position={[5.695, 0, -10.669]}>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.formation_rock_2 as THREE.Mesh)?.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.formation_rock_3 as THREE.Mesh)?.geometry}
            material={materials.sand}
          />
        </group>
      )}
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/formation_rock.gltf");
