/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three"; // Import THREE
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF(
    "/pirateKit/Models/glTF/formation_stone.gltf",
  );

  return (
    <group {...props}>
      {nodes && materials && (
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.formation_stone_1 as THREE.Mesh)?.geometry}
          material={materials.stone}
          position={[4.635, 0, -7.942]}
          rotation={[Math.PI, 0, Math.PI]}
        />
      )}
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/formation_stone.gltf");
