/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/formationLarge_stone.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.formationLarge_stone_1.geometry}
        material={materials.stone}
        position={[2.683, 0, -8.032]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1, 0.77, 1]}
      />
    </group>
  );
}

useGLTF.preload("/formationLarge_stone.gltf");
