/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three"; // Import THREE
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF(
    "/pirateKit/Models/glTF/formationLarge_rock.gltf",
  );

  return (
    <group {...props}>
      <group position={[4.045, 0, -10.639]} scale={[1, 0.77, 1]}>
        {nodes && materials && (
          <>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.formationLarge_rock_2 as THREE.Mesh)?.geometry}
              material={materials.wood}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.formationLarge_rock_3 as THREE.Mesh)?.geometry}
              material={materials.sand}
            />
          </>
        )}
      </group>
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/formationLarge_rock.gltf");
