/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF(
    "/pirateKit/Models/glTF/formation_rock.gltf",
  );
  return (
    <group {...props} dispose={null}>
      <group position={[5.695, 0, -10.669]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.formation_rock_2.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.formation_rock_3.geometry}
          material={materials.sand}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/formation_rock.gltf");
