/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF("/pirateKit/Models/glTF/hole.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[-4.775, 0, -6.052]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hole_2.geometry}
          material={materials.sand}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hole_3.geometry}
          material={materials.iron}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/hole.gltf");
