/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";
import { isMeshType } from "../../utils/isMeshType";
export function Model(props: ModelProps) {
  const { nodes } = useGLTF("/pirateKit/Models/glTF/paddle.gltf");
  return (
    <group {...props} dispose={null}>
      {isMeshType(nodes.paddle_1) && (
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.paddle_1.geometry}
          material={nodes.paddle_1.material}
          position={[-0.479, 0.37, -10.072]}
        />
      )}
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/paddle.gltf");
