/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF("/pirateKit/Models/glTF/paddle.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.paddle_1.geometry}
        material={materials.wood}
        position={[-0.479, 0.37, -10.072]}
      />
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/paddle.gltf");
