/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";
import { isMeshType } from "../../utils/isMeshType";
import { Group } from "three";

export function Model(props: ModelProps<Group>) {
  const { nodes, materials } = useGLTF(
    "/pirateKit/Models/glTF/palm_detailed_short.gltf"
  );
  return (
    <group {...props} dispose={null}>
      <group position={[2.706, 0, -7.168]}>
        {isMeshType(nodes.Group_18) && (
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Group_18.geometry}
            material={materials.wood}
            position={[-0.645, 0, 0.589]}
            scale={[0.766, 0.582, 0.766]}
          />
        )}
        {isMeshType(nodes.Group_20) && (
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Group_20.geometry}
            material={materials.leaves}
            position={[0, 1.278, 0]}
          />
        )}
      </group>
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/palm_detailed_short.gltf");
