/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";
import { isMeshType } from "../../utils/isMeshType";

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF("/pirateKit/Models/glTF/plant.gltf");
  return (
    <group {...props} dispose={null}>
      {isMeshType(nodes.plant_1) && (
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.plant_1.geometry}
          material={materials.leaves}
          position={[0.637, 0, -6.41]}
          scale={0.69}
        />
      )}
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/plant.gltf");
