/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/ship_wreck.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[9.255, 0, 0.014]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_1.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_2.geometry}
          material={materials.iron}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_3.geometry}
          material={materials.woodDark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_4.geometry}
          material={materials.window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_5.geometry}
          material={materials.leaves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_6.geometry}
          material={materials._defaultMat}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ship_wreck.gltf");
