/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import { ModelProps } from "../../types/ModelProps";

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF(
    "/pirateKit/Models/glTF/ship_wreck.gltf",
  );
  return (
    <group {...props} dispose={null}>
      <group position={[9.255, 0, 0.014]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_1.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_2.geometry}
          material={materials.iron}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_3.geometry}
          material={materials.woodDark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_4.geometry}
          material={materials.window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_5.geometry}
          material={materials.leaves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_6.geometry}
          material={materials._defaultMat}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/pirateKit/Models/glTF/ship_wreck.gltf");
